#!/bin/bash
set -e
source ./libs/logger.sh
source ./libs/conf_manager.sh

log_info "installing claude..."

if is_callable_from_path "claude"; then 
    log_info "\tclaude desktop app already installed"
else 
    if [[ "$OSTYPE" == "linux-gnu" ]]; then
        # LINUX
        log_error "IMPLEMENT THIS FOR LINUX !!!"
        exit 1
    elif [[ "$OSTYPE" == "darwin"* ]]; then
        # MAC OS
        brew install --cask claude
    else
        log_error "unsupported os: ($OSTYPE) !!!"
        exit 1
    fi
fi

if is_callable_from_path "claude-code"; then
    log_info "\tclaude-code CLI already installed"
else
    if [[ "$OSTYPE" == "linux-gnu" ]]; then
        # LINUX
        npm install -g @anthropic-ai/claude-code
    elif [[ "$OSTYPE" == "darwin"* ]]; then
        # MAC OS
        npm install -g @anthropic-ai/claude-code
    else
        log_error "unsupported os: ($OSTYPE) !!!"
        exit 1
    fi
fi

log_info "installing claude...DONE!" 