#!/bin/bash
set -e # set error to propmt (set +e)
source ./libs/logger.sh
source ./libs/conf_manager.sh

log_info "installing docker-compose..."
if [[ "$OSTYPE" == "linux-gnu" ]]; then
    # LINUX
    # echo "unsupported tool for LINUX"
    # TODO: check if wget is installed (sudo apt install wget)
    if is_callable_from_path "docker-compose"; then 
        log_info "\tdocker-compose already installed"
    else 
        log_warn "TODO - docker-compose linux installation not yet supported by scripts"
    fi

elif [[ "$OSTYPE" == "darwin"* ]]; then
    # MAC OS
    if is_callable_from_path "docker-compose"; then 
        log_info "\tdocker-compose already installed"
    else 
        brew install docker-compose
    fi
else
    log_error "unsupported os: ($OSTYPE) !!!"
    exit 1
fi
log_info "installing docker...DONE!"