#!/bin/bash
set -e
source ./libs/logger.sh
source ./libs/conf_manager.sh


log_info "installing kubectl..."

if is_callable_from_path "kubectl"; then 
    log_info "\tkubectl already installed"
else 
    if [[ "$OSTYPE" == "linux-gnu" ]]; then
        # LINUX
        snap install kubectl --classic
    elif [[ "$OSTYPE" == "darwin"* ]]; then
        # MAC OS
        brew install kubectl 
    else
        log_error "unsupported os: ($OSTYPE) !!!"
        exit 1
    fi
fi

log_info "installing kubectl...DONE!"